### ISSUE TITLE
Incorrect solution validator behavior

### ISSUE THREAD

**Issue by black220sun** [mchug/contest-cities-game#4]
https://github.com/mchug/contest-cities-game/blob/51519219fd2c11cb65f6b30a110187119fa2dc9a/src/main/java/com/itkpi/java/contest/cities/solution/SolutionValidator.java#L68-L74

`prevCity` and `nextCity` are equal at the first iteration, causing the validator to require equality of the first and the last letter for the first city name. Such behavior is either incorrect at all or at least should be mentioned in rules.

**Comment by mchuhaievskyi** [comment]
Thanks for your fix!
